version: '3'
services:
  clip_share_monitoring:
    restart: always
    build: .
    container_name: 'clip_share_monitoring'
    tty: true
    user: "1000:1000"
    volumes:
      - ./app:/home/appuser/app
      - /mnt/shared_folder/:/home/appuser/app/shared_folder/
    network_mode: host
    #command: python monitoring.py
    
  clip_share_http:
    restart: always
    build: .
    container_name: 'clip_share_http'
    tty: true
    user: "1000:1000"
    volumes:
      - ./app:/home/appuser/app
    network_mode: host
    command: python flask_server.py
